### PR TITLE
Make work with Rails 5

### PR DESCRIPTION
**Pull request by bquorning**
It looks like Rails 5 support should be pretty easy.

### CODE REVIEW

**Comment by dasch** [comment]
Looks good! :+1:

**Comment by sinisterchipmunk** [comment]
Thanks!

**Comment by bquorning** [comment]
Thank you :heart:

**Comment by bquorning** [comment]
Will you consider releasing a new patch/minor version, please?

**Comment by sinisterchipmunk** [comment]
Yup! As luck would have it, I was already planning to do so. I'm out for some hours yet but will publish the new version sometime today.

**Comment by sinisterchipmunk** [comment]
Released 0.3.0, thanks!

**Pull request merged**
